import "./globals.css";
import type { Metadata } from "next";
import { kanit } from "@/lib/fonts/font";
import { getServerSession } from "next-auth";
import Link from "next/link";
import Logout from "@/components/shared/Logout";
export const metadata: Metadata = {
  title: "Hunt",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={kanit.className}>
        <div>
          {!!session && (
            <span>
              <Logout />
            </span>
          )}
          {!session && <Link href="/signin">Login</Link>}
        </div>
        {children}
      </body>
    </html>
  );
}
