import "./globals.css";
import type { Metadata } from "next";
import { kanit, rale } from "@/lib/fonts/font";
import { getServerSession } from "next-auth";
import AuthProvider from "@/utils/Provider";

export const metadata: Metadata = {
  title: "Hunt",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={`${kanit.variable} ${rale.variable}`}>
        <AuthProvider session={session}>{children}</AuthProvider>
      </body>
    </html>
  );
}
