export const EventData = [
  {
    id: "1",
    title: "CodeCrafters Unleashed: A Developer's Odyssey",
    content: `"CodeCrafters Unleashed: A Developer's Odyssey" is not just another tech event—it's an immersive journey into the heart of the developer's universe. Embark on an odyssey where lines of code transform into narratives, bugs become challenges to conquer, and innovation is the compass guiding the way. This event is a celebration of the artistry and ingenuity of developers, uniting coding enthusiasts, seasoned professionals, and aspiring learners in an environment designed to inspire, educate, and spark collaboration. From deep-dives into cutting-edge technologies to hands-on coding challenges, attendees will traverse the vast landscapes of software development, unlocking new realms of creativity and pushing the boundaries of what's possible in the digital realm. Join us on this exhilarating voyage at "CodeCrafters Unleashed," where every line of code is a step in your developer's odyssey. Are you ready to unleash the coder within?`,
    start: "10.00",
    end: "12.00",
    date: "11/20/2023",
    location: "California",
  },
  {
    id: "2",
    title: "Innovate or Evaporate: The Future of Tech",
    content: `"CodeCrafters Unleashed: A Developer's Odyssey" is not just another tech event—it's an immersive journey into the heart of the developer's universe. Embark on an odyssey where lines of code transform into narratives, bugs become challenges to conquer, and innovation is the compass guiding the way. This event is a celebration of the artistry and ingenuity of developers, uniting coding enthusiasts, seasoned professionals, and aspiring learners in an environment designed to inspire, educate, and spark collaboration. From deep-dives into cutting-edge technologies to hands-on coding challenges, attendees will traverse the vast landscapes of software development, unlocking new realms of creativity and pushing the boundaries of what's possible in the digital realm. Join us on this exhilarating voyage at "CodeCrafters Unleashed," where every line of code is a step in your developer's odyssey. Are you ready to unleash the coder within?`,
    start: "11.00",
    end: "2.00",
    date: "8/20/2023",
    location: "Austria",
  },
  {
    id: " 3",
    title: "Byte Me: Navigating the World of Microservices",
    content: `"CodeCrafters Unleashed: A Developer's Odyssey" is not just another tech event—it's an immersive journey into the heart of the developer's universe. Embark on an odyssey where lines of code transform into narratives, bugs become challenges to conquer, and innovation is the compass guiding the way. This event is a celebration of the artistry and ingenuity of developers, uniting coding enthusiasts, seasoned professionals, and aspiring learners in an environment designed to inspire, educate, and spark collaboration. From deep-dives into cutting-edge technologies to hands-on coding challenges, attendees will traverse the vast landscapes of software development, unlocking new realms of creativity and pushing the boundaries of what's possible in the digital realm. Join us on this exhilarating voyage at "CodeCrafters Unleashed," where every line of code is a step in your developer's odyssey. Are you ready to unleash the coder within?`,
    start: "11.00",
    end: "2.30",
    date: "9/29/2023",
    location: "Austria",
  },
  {
    id: "4",
    title: "The DevOps Dilemma: Bridging the Gap between Dev and Ops",
    content: `"CodeCrafters Unleashed: A Developer's Odyssey" is not just another tech event—it's an immersive journey into the heart of the developer's universe. Embark on an odyssey where lines of code transform into narratives, bugs become challenges to conquer, and innovation is the compass guiding the way. This event is a celebration of the artistry and ingenuity of developers, uniting coding enthusiasts, seasoned professionals, and aspiring learners in an environment designed to inspire, educate, and spark collaboration. From deep-dives into cutting-edge technologies to hands-on coding challenges, attendees will traverse the vast landscapes of software development, unlocking new realms of creativity and pushing the boundaries of what's possible in the digital realm. Join us on this exhilarating voyage at "CodeCrafters Unleashed," where every line of code is a step in your developer's odyssey. Are you ready to unleash the coder within?`,
    start: "8.00",
    end: "2.30",
    date: "12/29/2023",
    location: "Austria",
  },
  {
    id: "5",
    title: "AI Wonderland: Demystifying Artificial Intelligence",
    content: `"CodeCrafters Unleashed: A Developer's Odyssey" is not just another tech event—it's an immersive journey into the heart of the developer's universe. Embark on an odyssey where lines of code transform into narratives, bugs become challenges to conquer, and innovation is the compass guiding the way. This event is a celebration of the artistry and ingenuity of developers, uniting coding enthusiasts, seasoned professionals, and aspiring learners in an environment designed to inspire, educate, and spark collaboration. From deep-dives into cutting-edge technologies to hands-on coding challenges, attendees will traverse the vast landscapes of software development, unlocking new realms of creativity and pushing the boundaries of what's possible in the digital realm. Join us on this exhilarating voyage at "CodeCrafters Unleashed," where every line of code is a step in your developer's odyssey. Are you ready to unleash the coder within?`,
    start: "9.00",
    end: "3.30",
    date: "12/29/2023",
    location: "Austria",
  },
];
